Repository indomie858/app-A, pull requests merged in 2021-03, with the labels that each got.

#122 Added map button to DirectionsActivity
  app/src/main/java/com/example/appa/ui/navigation/DirectionsActivity.kt
  app/src/main/res/drawable/ic_baseline_map_24.xml
  app/src/main/res/layout/activity_directions.xml
  app/src/main/res/layout/nav_list_activity.xml
  app/src/main/res/menu/top_app_bar_directory.xml
  app/src/main/res/menu/top_app_bar_mapbox.xml
Labels: Mapbox, UI

#124 Added splash screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/appa/ui/MainActivity.java
  app/src/main/res/drawable-v24/appa_white_font.png
  app/src/main/res/drawable/splash.xml
  app/src/main/res/values/styles.xml
Labels: UI, enhancement

#127 Issue105 distance warnings
  app/src/main/java/com/example/appa/bluetooth/BTConnectionHelper.java
  app/src/main/java/com/example/appa/bluetooth/MessageConstants.java
  app/src/main/java/com/example/appa/bluetooth/SensorReadingSingleton.java
  app/src/main/java/com/example/appa/ui/MainActivity.java
  app/src/main/java/com/example/appa/ui/mapbox/DirectionsActivity.kt
  app/src/main/res/raw/chime_bell_ding.wav
Labels: enhancement

#129 Issue88 bug fitness
  app/src/main/assets/locations.db
  app/src/main/java/com/example/appa/ui/MainActivity.java
  app/src/main/java/com/example/appa/ui/home/HomeAdapter.java
  app/src/main/java/com/example/appa/ui/home/HomeFragment.kt
  app/src/main/res/layout/home_layout.xml
  app/src/main/res/values/strings.xml
Labels: bug

#132 Issue97 see more directory
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/appa/ui/navigationlist/DirectoryInformationActivity.java
  app/src/main/java/com/example/appa/ui/navigationlist/PlaceAdapter.java
  app/src/main/res/layout/activity_directory_information.xml
  app/src/main/res/layout/place_tile.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#141 tts audio bug fix
  app/src/main/java/com/example/appa/ui/navigationlist/DirectoryInformationActivity.java
Labels: bug

#143 Issue142 back nav bug
  app/src/main/java/com/example/appa/ui/mapbox/DirectionsActivity.kt
  app/src/main/java/com/example/appa/ui/navigationlist/DirectoryInformationActivity.java
Labels: bug

#155 changed bottom nav button active color
  app/src/main/res/color/bottom_nav_color.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/xml/root_preferences.xml
Labels: UI

#158 Restyle directory information activity
  app/src/main/res/layout/activity_directory_information.xml
Labels: UI
