Repository indomie858/app-A, pull requests merged in 2021-02, with the labels that each got.

#112 Updated mapbox UI
  app/src/main/java/com/example/appa/bluetooth/BTConnectionHelper.java
  app/src/main/java/com/example/appa/ui/navigation/DirectionsActivity.kt
  app/src/main/java/com/example/appa/ui/navigation/DirectionsAdapter.java
  app/src/main/res/drawable/ic_baseline_exit_to_app_24.xml
  app/src/main/res/drawable/ic_baseline_refresh_24.xml
  app/src/main/res/layout/activity_directions.xml
  app/src/main/res/layout/destination_row.xml
  app/src/main/res/layout/maneuver_row.xml
  app/src/main/res/menu/bottom_app_bar.xml
Labels: Mapbox, UI, enhancement

#115 Issue89 bearing
  app/src/main/java/com/example/appa/ui/navigation/CompassActivity.java
  app/src/main/java/com/example/appa/ui/navigation/DirectionsActivity.kt
  app/src/main/java/com/example/appa/ui/navigation/DirectionsAdapter.java
  app/src/main/java/com/example/appa/viewmodel/CompassViewModel.java
  app/src/main/res/layout/compass_layout.xml
  app/src/main/res/layout/destination_row.xml
  app/src/main/res/menu/bottom_app_bar.xml
Labels: UI

#119 Implemented distance unit setting in mapbox
  app/src/main/java/com/example/appa/ui/navigation/DirectionsActivity.kt
  app/src/main/java/com/example/appa/ui/navigation/DirectionsAdapter.java
Labels: enhancement

#116 Merging latest changes from dev
  app/src/main/AndroidManifest.xml
  app/src/main/assets/locations.db
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/example/appa/bluetooth/BTConnectionHelper.java
  app/src/main/java/com/example/appa/bluetooth/BluetoothHandler.java
  app/src/main/java/com/example/appa/bluetooth/BluetoothServiceHandler.java
  app/src/main/java/com/example/appa/bluetooth/MessageConstants.java
  app/src/main/java/com/example/appa/db/PlaceRepository.java
  app/src/main/java/com/example/appa/ui/BluetoothDialog.java.bak
  app/src/main/java/com/example/appa/ui/MainActivity.java
  app/src/main/java/com/example/appa/ui/navigation/CompassActivity.java
  app/src/main/java/com/example/appa/ui/navigation/DirectionsActivity.kt
  app/src/main/java/com/example/appa/ui/navigation/DirectionsAdapter.java
  app/src/main/java/com/example/appa/ui/navigationlist/NavigationListActivity.java
  app/src/main/java/com/example/appa/ui/navigationlist/PlaceAdapter.java
  app/src/main/java/com/example/appa/ui/settings/SettingsFragment.kt
  app/src/main/java/com/example/appa/viewmodel/CompassViewModel.java
  app/src/main/java/com/example/appa/viewmodel/PlaceViewModel.java
  app/src/main/res/drawable-v24/appa.png
  app/src/main/res/drawable-v24/appa_no_text.png
  app/src/main/res/drawable-v24/ic_launcher_background.xml
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable-v24/pointer.png
  app/src/main/res/drawable/ic_baseline_exit_to_app_24.xml
  app/src/main/res/drawable/ic_baseline_refresh_24.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_compass.xml
  app/src/main/res/layout/activity_directions.xml
  app/src/main/res/layout/activity_instruction_view_layout.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/compass_layout.xml
  app/src/main/res/layout/destination_row.xml
  app/src/main/res/layout/maneuver_row.xml
  app/src/main/res/menu/bottom_app_bar.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/root_preferences.xml
Labels: Mapbox, UI, bug, enhancement
